In [2]:
import torch
import torch.nn.functional as F

torch.manual_seed(1)

## 1. low level

In [3]:
z = torch.FloatTensor([1, 2, 3])

In [4]:
h = F.softmax(z, dim=0)

In [6]:
print(h)

tensor([0.0900, 0.2447, 0.6652])


In [7]:
h.sum()

tensor(1.)

In [8]:
z = torch.rand(3, 5, requires_grad=True)

In [10]:
h = F.softmax(z, dim=1)
print(h)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [53]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([0, 3, 2])


In [55]:
y_one_hot = torch.zeros_like(h)

In [58]:
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])

In [59]:
cost = (y_one_hot * -torch.log(h)).sum(dim=1).mean()

In [60]:
print(cost)

tensor(1.4779, grad_fn=<MeanBackward0>)


## 2. high level

In [61]:
(y_one_hot * - F.log_softmax(z, dim=1)).sum(dim=1).mean()

tensor(1.4779, grad_fn=<MeanBackward0>)

In [63]:
# 원-핫 벡터 넣을 필요 없이
F.nll_loss(F.log_softmax(z, dim=1), y)

tensor(1.4779, grad_fn=<NllLossBackward0>)

In [64]:
F.cross_entropy(z, y)

tensor(1.4779, grad_fn=<NllLossBackward0>)