In [11]:
import torch
import torch.nn as nn
import torch.optim as optim

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [4]:
print(device)

cuda


In [5]:
torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [8]:
X = torch.FloatTensor([[0,0], [0, 1], [1, 0], [1,1]]).to(device)
Y = torch.FloatTensor([[0],[1], [1], [0]]).to(device)

In [10]:
model = nn.Sequential(
    nn.Linear(2, 10, bias = True),
    nn.Sigmoid(),
    nn.Linear(10, 10, bias = True),
    nn.Sigmoid(),
    nn.Linear(10,1, bias = True),
    nn.Sigmoid()
).to(device)

In [13]:
criterion = torch.nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=1)

In [14]:
for epoch in range(10001):
  optimizer.zero_grad()
  h = model(X)
  cost = criterion(h, Y)
  cost.backward()
  optimizer.step()

  if epoch % 100 ==0:
    print(epoch, cost.item())

0 0.7293977737426758
100 0.6930801868438721
200 0.6930012702941895
300 0.6928911209106445
400 0.6927139759063721
500 0.6923817992210388
600 0.6916359663009644
700 0.6895250082015991
800 0.6815847158432007
900 0.641865611076355
1000 0.49458175897598267
1100 0.10047123581171036
1200 0.02146078646183014
1300 0.009944304823875427
1400 0.006086558103561401
1500 0.0042627290822565556
1600 0.003228446003049612
1700 0.0025724710430949926
1800 0.0021237721666693687
1900 0.001799705089069903
2000 0.001555921626277268
2100 0.001366511918604374
2200 0.0012155793374404311
2300 0.0010927439434453845
2400 0.0009910711087286472
2500 0.0009055665577761829
2600 0.0008327962714247406
2700 0.0007702093571424484
2800 0.0007158206426538527
2900 0.0006681581726297736
3000 0.000626087246928364
3100 0.0005887314327992499
3200 0.000555315928068012
3300 0.0005252617411315441
3400 0.0004981120000593364
3500 0.0004734884132631123
3600 0.0004510431899689138
3700 0.00043051899410784245
3800 0.0004116708296351135
390

In [15]:
with torch.no_grad():
  h = model(X)
  predicted = (h > 0.5).float()
  accuracy = (predicted==Y).float().mean()

  print(h.detach().cpu().numpy())
  print(predicted.detach().cpu().numpy())
  print(Y.cpu().numpy())
  print(accuracy.item)

[[7.57357193e-05]
 [9.99885321e-01]
 [9.99896765e-01]
 [1.19008255e-04]]
[[0.]
 [1.]
 [1.]
 [0.]]
[[0.]
 [1.]
 [1.]
 [0.]]
<built-in method item of Tensor object at 0x7fcf5aaca6d0>
